### ISSUE TITLE
missing dependency to usethis

### ISSUE THREAD

**Issue by ginolhac** [toddgrabowsky/tarflow#2]
Hello,

thanks for developing this nice package. I am using `tarflow::use_tarflow()` in a clean `renv` and it seems that the dependency to `usethis` is not specify in your DESCRIPTION and thus missing.

Best regards

**Comment by toddgrabowsky** [comment]
@ginolhac thanks so much for the feedback! Just pushed a minor change to add usethis to the imports in the DESCRIPTION file.
